package com.mrcd.xrouter;

import com.mrcd.xrouter.core.IntentInterceptor;
import com.xxc.xrouter.routers.AppMainRouter;
import com.xxc.xrouter.routers.DemoActivityRouter;
import com.xxc.xrouter.routers.MainSecondActivityRouter;
import com.xxc.xrouter.routers.MainThirdActivityRouter;

/**
 * Generated by XRouter, please do not modify
 */
public final class XRouter {
  private static XRouter INSTANCE = new XRouter();

  private IntentInterceptor mGlobalInterceptor;

  private XRouter() {
  }

  public static XRouter getInstance() {
    return INSTANCE;
  }

  public void setGlobalInterceptor(IntentInterceptor interceptor) {
    mGlobalInterceptor = interceptor;
  }

  public MainThirdActivityRouter mainThirdActivity() {
    return new MainThirdActivityRouter().setInterceptor(mGlobalInterceptor);
  }

  public MainSecondActivityRouter mainSecondActivity() {
    return new MainSecondActivityRouter().setInterceptor(mGlobalInterceptor);
  }

  public AppMainRouter appMain() {
    return new AppMainRouter().setInterceptor(mGlobalInterceptor);
  }

  public DemoActivityRouter demoActivity() {
    return new DemoActivityRouter().setInterceptor(mGlobalInterceptor);
  }
}
